plugins:
  reader:
    Twacapic:
      description: "A twacapic reader"
      moduleName: ".Reader.TwacapicReader"
      className: "TwacapicReader"
  writer:
    CSV:
      moduleName: ".Writer.CSVWriter"
      className: "CSVWriter"
    SMODBTwitter:
      moduleName: ".Writer.SMODBTwitter"
      className: "SMODBTwitter"
      config:
        dbuser: "postgres"
        dbpass: "postgres"
        dbname: "smo"
