!dabapush:Configuration
readers:
  Twacapic:
    description: "A twacapic reader"
    moduleName: ".Reader.TwacapicReader"
    className: "TwacapicReaderConfiguration"
writers:
  CSV:
    moduleName: ".Writer.CSVWriter"
    className: "CSVWriter"
  NDJSON:
    moduleName: ".Writer.NdjsonWriter"
    className: "NdjsonWriter"
  SMODBTwitter:
    moduleName: ".Writer.SMODBTwitter"
    className: "SMODBTwitter"
    config:
      dbuser: "postgres"
      dbpass: "postgres"
      dbname: "smo"
