!dabapush:Registry
readers:
  Twacapic:
    description: "A twacapic reader"
    moduleName: ".Reader.TwacapicReader"
    className: "TwacapicReaderConfiguration"
  NDJSON:
    description: "Read NDJSON"
    moduleName: ".Reader.NDJSONReader"
    className: "NDJSONReaderConfiguration"
writers:
  CSV:
    moduleName: ".Writer.CSVWriter"
    className: "CSVWriterConfiguration"
  NDJSON:
    moduleName: ".Writer.NDJSONWriter"
    className: "NDJSONWriterConfiguration"
  SMOTW:
    moduleName: ".Writer.TwitterDBWriter"
    className: "TwitterDBWriterConfiguration"
  SMOFB:
    moduleName: ".Writer.FacebookDBWriter"
    className: "FacebookDBWriterConfiguration"
  SMOIG:
    moduleName: ".Writer.InstagramDBWriter"
    className: "InstagramDBWriterConfiguration"
  SMODBOES:
    moduleName: ".Writer.FacebookDBWriter"
    className: "FacebookDBWriterConfiguration"
