!dabapush:Registry
readers:
  Twacapic:
    description: "A twacapic reader"
    moduleName: ".Reader.TwacapicReader"
    className: "TwacapicReaderConfiguration"
writers:
  CSV:
    moduleName: ".Writer.CSVWriter"
    className: "CSVWriterConfiguration"
  NDJSON:
    moduleName: ".Writer.NDJSONWriter"
    className: "NDJSONWriterConfiguration"
  SMODBTwitter:
    moduleName: ".Writer.SMODBTwitter"
    className: "SMODBTwitterConfiguration"
    config:
      dbuser: "postgres"
      dbpass: "postgres"
      dbname: "smo"
